// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdbntjxombggmkaskxhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkYm50anhvbWJnZ21rYXNreGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTc0ODcsImV4cCI6MjA3MjI5MzQ4N30.HJfUxDDnsarP0KxVnwCss9E-n6Dxy7h7ODpUPCblJsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});